#!/bin/sh
cd /home/ircbot/wogbot
#export CLASSPATH='./irclib.jar:jaxp-1.3.jar:jdom.jar:.:/usr/lib/jvm/java-6-sun-1.6.0.03/jre/lib/rt.jar:WogBot.jar'
#export CLASSPATH="WogBot.jar"
java -Xmx1024M -jar WogBot.jar 2> stderr
#java -Xmx512M core.BotMain 2> stderr
